### ISSUE TITLE
giffgaff namespace is used in some places

### ISSUE THREAD

**Issue by rob006** [flarumite/flarum-decontaminator#4]
https://github.com/flarumite/flarum-decontaminator/blob/06ac671ed28a65a7e3d845af126946c5c627d48d/js/src/admin/components/EditDecontaminatorRuleModal.js#L151

https://github.com/flarumite/flarum-decontaminator/blob/1bea57d8acdb70bd53c02844f52df4601c6551a8/src/Command/DeleteProfanityHandler.php#L44

**Comment by imorland** [comment]
Good spot, thanks!
